AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  response-check

  Sample SAM Template for response-check

Globals:
  Function:
    Timeout: 120
    Handler: app.lambda_handler
    Runtime: ruby2.5
    MemorySize: 256

Resources:
  CheckResponseStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: s3://[bucket_name]/statemachine/check_response_v2.json
      DefinitionSubstitutions:
        CheckResponseFunctionArn: !GetAtt CheckResponseFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref CheckResponseFunction

  CheckResponseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/check_response/


Outputs:
  CheckResponseStateMachineArn:
    Description: "State machine ARN"
    Value: !Ref CheckResponseStateMachine
  CheckResponseStateMachineRole:
    Description: "IAM Role created for State machine based on the specified SAM Policy Templates"
    Value: !GetAtt CheckResponseStateMachineRole.Arn
